### ISSUE TITLE
Using Near with PostgreSQL fails (heroku)

### ISSUE THREAD

**Issue by davidtolsma** [alexreisner/geocoder#107]
When deploying to Heroku, and using near, it fails. Heroku's default  PostgreSQL.

@locations = Location.all # WORKS

@locations = Location.near(params[:search], 50, :order => :distance) # FAILS

Rails 3.0.9
geocoder 1.0.2
PostgreSQL 8.4

**Comment by MaxPleaner** [comment]
Acknowledging this issue is closed, it is still a top Google result when searching for the error.

I'm just going to throw in my 2 cents regarding the situation I was in and what fixed it.

For me the problem was as simple as `User.pluck(:id)` (which caused the error) vs. `User.select(:id).map(&:id)`

I don't know what happens internally here and I have only appreciation for this gem which I've used multiple times. Hopefully this will help someone though.

**Comment by xyingsoft** [comment]
Hi, Alex, Thanks for your great work.
I have similar problem. 
My table has 'distance' column, but I don't want to change rename it.

It would be great if I could solve this problem like following:
Route.nearby([lat, lon], radius, distance_column: :nearby_distance)
