### ISSUE TITLE
Could use new sqlite_ext gem to make SQLite results better

### ISSUE THREAD

**Issue by stevecj** [alexreisner/geocoder#1073]
I recently had reason to want to use geocoder with SQLite in a Rails app. It was for a coding challenge, and the inaccuracy of results using SQLite did not really matter. It still bothered me though.

As a result of that, I decided to look into whether the needed functionality could be added to SQLite in Ruby in a reasonably clean and simple way, and I found out that there is. It wasn't quite convenient to use, but I have been able to develop a gem (sqlite_ext) that makes it convenient.

Could we have geocoder check to see if the sqlite_ext gem is loaded, and in that case, call SqliteExt.register_ruby_math and then use the added SQL functions to compute distance and vector properly in SQLite queries?

See https://github.com/stevecj/sqlite_ext

**Comment by alexreisner** [comment]
Nice! I played around with doing this years ago but didn't get very far. Good work.

I'm a little hesitant about adding this kind of support because most of the time the accuracy in SQLite just doesn't matter (though it does bother me, too), and I make an effort to keep this gem's code as simple as possible while serving all of the most common needs. That said, if there was a PR showing how this could be done with very minimal complexity added, I'd be awfully tempted to merge...

Regardless, again, nice work on sqlite_ext!

(@TrangPham: any thoughts on this?)

**Comment by TrangPham** [comment]
I really like the idea of supporting different databases.

I agree with your concerns with simplicity. And I ask worry about
maintenance of supporting other databases.

We still have errors in our mangoDB support. I would be very happy if
sqlite_ext is able to handle the support for this.

**Comment by stevecj** [comment]
I have added PR https://github.com/alexreisner/geocoder/pull/1076 which is failing CI because the sqlite_ext gem is apparently not getting into the gemset. May I have some help figuring out how to get that right in Gemfile?

**Comment by stevecj** [comment]
I think that I have PR #1076 in excellent shape now.

**Comment by alexreisner** [comment]
Solved by #1076.
