### ISSUE TITLE
Adhere to semantic versioning

### ISSUE THREAD

**Issue by PragTob** [alexreisner/geocoder#1080]
Hi there,

thanks for the geocoding gem - I've used it on a number of occasions and quite liked it :)

Looking to update it in a bigger application today, I glanced at the [Changelog](https://github.com/alexreisner/geocoder/blob/master/CHANGELOG.md) today and was a bit surprised by the breaking changes happening in what are patch level updates in semver. 

* 1.2.4 dropped a whole geocoding service
* 1.2.7 dropped support for all of ruby 1.9.2

I'd propose that going forward, versions would/could be semver-ish. I mean optimally those would be in major version bumps (imo). Personally I could also live with them happening in minor version bumps, but imo patch level updates should be reserved for fixes - i.e. updating from 1.2.x to 1.2.y should be doable without any fear.

What do you think?

**Comment by alexreisner** [comment]
@PragTob I totally agree. I was a little careless in removing Ruby 1.9.2 support. That probably should have been done in 1.3.0. Removing support for Coudmade in 1.2.4 (and later for Yahoo) is not quite the same thing, though, because the service was shut down, rendering the code useless/misleading (anyone using it had to change their lookup anyway, regardless of gem version). That kind of thing will continue to happen and I don't think it warrants a major/minor version increase. But I agree that we should be more careful with other aspects of the gem.
