### ISSUE TITLE
Bulk geocoding don't work

### ISSUE THREAD

**Issue by nicolaswecandoit** [alexreisner/geocoder#1086]
Hey,

I have more than 5000 adress in database. When i edit one specific entry geocode system work, but if I try to bulk all my database nothing happen.

So whats wrong ?
Thanks for your help :)

**My model**
```
def fulladress
    [street,zipcode,city].to_a.compact.join(",")
end
geocoded_by :fulladress
after_validation :geocode
```

**Comment by alexreisner** [comment]
I think the first step in debugging this is to run rake with the `-t` option and see if it gives any insight into what's failing. Also, does it take a long time to run or is it exiting quickly?

**Comment by nicolaswecandoit** [comment]
At the first time, thanks for your reply. So when I m runing -t option i have this message =>![geocode](https://cloud.githubusercontent.com/assets/20522854/18357246/7cf91a26-75f0-11e6-889c-886a3774017d.png)
It takes long time like 2 minute. But nothing happen. After stop, my adress wasnt geocoding. So whats wrong ?

**Comment by alexreisner** [comment]
If it takes 2 minutes to run then it sounds like it's loading and saving your objects. You might want to add some debugging code to your model, or running the `geocode:all` steps in a console. E.g.:

1. check that `YourModel.not_geocoded` returns un-geocoded objects,
2. check that calling `.geocode` on one of the objects results in successful geocoding, and
3. check that calling `.save` on the object saves it successfully.

One common problem is an unrelated validation issue preventing the objects from being saved.

Closing because this doesn't seem like a Geocoder bug, but please reopen if there's evidence that it is one.
