### ISSUE TITLE
Built-in support for custom lookup class

### ISSUE THREAD

**Issue by dexterouschen** [alexreisner/geocoder#1106]
I tried to monkey-patch Geocoder since the service I'm using is not officially supported, but I do have to override a bunch of public/private classes for the purpose.

The main issues here I see are:
1. Hard-coded list of support services, I can totally override the list, but there should be a more convenient way to do so. Is it possible to dynamically load all needed classes? Or is there any significant benefit for only requiring a class for spawn? We can obtain a list of all services configured and require all of them right?
2. Hard-coded support for only JSON format, again, I can override it, but XML response is also very common, can it be an official option? It can be a part of the configuration, even better, make it available for service-specific configuration.

**Comment by TrangPham** [comment]
Hi

We don't support monkey-patching well. This is mostly because we are very
open to everyone adding support for specific services directly to geocoder
gem. This is part of the reason why "there is significant benefit for only
requiring a class for spawn". Since we don't want geocoder to be heavy if
you're only going to use a specific service.

1. Though having a way to dynamically require a class during execution may
be a good idea. I'm not sure what the use cases of this are. Maybe the best
implementation of this is when Geocoder.configure() is called to ensure the
lookup is require/loaded.

2. Adding XML response handling is a good feature to have. I recommend that
the configuration options be within the lookup file itself.

Thanks,
Thu
