### ISSUE TITLE
.distance does not work when a collection has been filtered using .where

### ISSUE THREAD

**Issue by saratateno** [alexreisner/geocoder#1108]
Hi there,

I've been trying a few different things and think I might have found a bug? I have a collection: `@addresses  = Address.near(...).`

Calling `.distance` on any of the records in this collection works fine. It also continues to work with various finder methods called on this collection. However, if I use `.where`, then distance method is undefined.

i.e.
`@addresses.find_by(house: "My place").distance`   --> this works
`@addresses.where(house: "My place").distance` --> this doesn't

I need to filter on conditions / scope from an associated model. I'm a fairly newbie programmer and don't know if there is a sensible work around as an alternative to using `.where` (please let me know if there is!). I had a dig around in your files but don't know why this arises, or how to suggest a fix for it.. sorry!

Brilliant gem otherwise. 👍 

Thanks!

**Comment by lime** [comment]
If I'm reading it right, it looks like you may have missed the fact that `.find` & `.find_by` return a _single_ record, while `.where` returns _multiple_ records that match the criteria.

`.find_by` gives you a single `Address`. Because you used `.near` earlier to filter the addresses, this address has an additional `.distance` attribute.

`.where` gives you a list (a "relation") of `Address` objects. Each of the addresses has the `.distance` attribute, so if you e.g. loop through them you can call `.distance` on each one:

```rb
@addresses.where(house: "My place").each do |address|
  # do something with each address
  puts address.distance
end
```

Hopefully that helps. If I misunderstood the question, let me know. :)

**Comment by saratateno** [comment]
Ah! You're right - I had missed that on my example...

There was something else going on in my actual app which led me to that bit of (erroneous) investigation!

My page renders fine using `.near` and also using `.includes`, but then if I add the `.where` bit of the query in order to refine the results, it says the distance method doesn't exist on the address object. 

This is the query:
```
@addresses = Address.near(session[:location] + ', UK', params[:distance]).includes(venue: :schedules).where("schedules.weekday = ?", Schedule.weekdays[params[:weekday].to_sym]).references(:schedules)
```

```
(byebug) @addresses.first
#<Address id: 62, ... >
(byebug) @addresses.first.distance
*** NoMethodError Exception: undefined method `distance' for #<Address:0x007fab63d93350>
Did you mean?  distance_to
```

Query appears to return the correct addresses otherwise, but I can't then render the page. I tried workaround using `.distance_to(session[:location])` on the view but that makes it render incredibly slowly.

Thanks for your help. :)

**Comment by Owumaro** [comment]
I encountered the same issue. The computed `distance` values aren't mapped back to the model when I use `.near` with `.includes`. I found a rails issue about this :
https://github.com/rails/rails/issues/15185

A quick solution is to use `.join` instead of `.includes`. However if you need fields from your other tables, you don't really want to use `.join`.
They also suggest this gem (I haven't tried it) : https://github.com/alekseyl/rails_select_on_includes

**Comment by rgallison** [comment]
I'm having a similar problem.  I narrowed it down to using `references`.  the second I add that, my distances disappear.  if I just use `includes`, I still have them.

**Comment by alexreisner** [comment]
@Owumaro and @rgallison you cannot use `includes` with `near`. This is mentioned [in the README.](https://github.com/alexreisner/geocoder#known-issue)
