### ISSUE TITLE
Pass query options through geocoded_by?

### ISSUE THREAD

**Issue by toppa** [alexreisner/geocoder#1118]
I'm trying to figure out if it's possible to pass query options with `geocoded_by` - I don't see this mentioned in the docs. Specifically, I want to pass arguments to the Googe API's `components` parameter. I can do it with `Geocoder.search`, but I don't see how to do it with my method that's invoked by `geocoded_by` - it seems to want only a single string returned, and if I correctly understand its option for passing a block, it's for handling results. Is it possible to do this?

**Comment by TrangPham** [comment]
Hi @toppa 

There are a few things that you could pass to `geocoded_by`. You can see those options here: https://github.com/alexreisner/geocoder/blob/6589b9b2cd6d1cdda06bd1f598fe9ad070d8e5a9/lib/geocoder/models/active_record.rb#L11-L22

But currently no way to handle passing params. We are open to accepting a pull request for this feature as this question has been asked before by others: https://github.com/alexreisner/geocoder/issues/765

Currently this can be achieved only by writing custom geocode method. See the linked issue for example. 

Thanks!

**Comment by toppa** [comment]
Thanks for the quick reply. It looks like we would need to [open this up](6589b9b2cd6d1cdda06bd1f598fe9ad070d8e5a9/lib/geocoder/stores/base.rb#L93) to allow for user supplied params. This is my first time looking at the Geocoder internals, so I'm not sure offhand how `options[:user_address]` gets populated from the `:geocoded_by` method. But my thought is to maybe add support for something like `:geocoded_by_params` which would populate a new `options[:user_params]`, which we could add to that `query_options` hash. Does that general idea make sense?

**Comment by TrangPham** [comment]
@toppa That is correct. `options[:user_params]` should be adding into the `query_options`

Instead of `:geocoded_by_params`, I would suggest just calling it `:params` to match the style of the search function. This would also be nicer on `reverse_geocoded_by`. So that calling would look like:

```ruby
geocoded_by :address, :params => {region: 'US'}

reverse_geocoded_by :lat, :lon, :params => {region: 'US'}
```

Here is where the `:user_address` is coming from: https://github.com/alexreisner/geocoder/blob/6589b9b2cd6d1cdda06bd1f598fe9ad070d8e5a9/lib/geocoder/models/active_record.rb#L14

I didn't 100% get how it gets from there to the `do_lookup` function itself. It's getting the geocoder_options from the class that's calling into do_lookup I believe - but then geocoder_options is actually defined in the model base class not the store base class: https://github.com/alexreisner/geocoder/blob/6589b9b2cd6d1cdda06bd1f598fe9ad070d8e5a9/lib/geocoder/models/base.rb#L9. 
And do_lookup is called from the store classes: https://github.com/alexreisner/geocoder/blob/6589b9b2cd6d1cdda06bd1f598fe9ad070d8e5a9/lib/geocoder/stores/active_record.rb#L287
So there's a step I'm missing here. Maybe @alexreisner could explain more?

Thanks so much for wanting to add this feature! Please ensure to add some unit tests!

**Comment by TrangPham** [comment]
I think I will try to implement this 😶

**Comment by alexreisner** [comment]
Added by #1188.
