### ISSUE TITLE
Sometimes empty results cached for valid addresses

### ISSUE THREAD

**Issue by rdlugosz** [alexreisner/geocoder#1148]
Branching off discussion [started here](https://github.com/alexreisner/geocoder/issues/1089#issuecomment-274945995)…

It appears that the Google Geocoding API will sometimes reply with an empty result set for an otherwise good address (one that would normally produce one or more results). *Since this empty set is cached by the gem, future geocoding requests for this same address will also show no results*.

One such address that we saw in production was `5302 W Argyle St, Chicago, IL, United States`. I don't believe there is anything special with this address; it just happened to be one where we noticed this issue. (What led to discovery was a user saying our system couldn't find this address while google maps found it with no problem. Purging the cache (or just spelling the address slightly differently) resolved the error, indicating that our geocoder cache contained an empty result.)

Because the gem should only cache a `valid_response?` …it would seem that Google will occasionally return an `OK` or `ZERO_RESULTS` status in spite of an errant empty result set.

Not sure how to recreate the issue so tricky to diagnose a root cause. One solution that treats the symptom would be an ability to set a short expiration time on cached items with empty result sets.

**Comment by alexreisner** [comment]
@rdlugosz Have you learned any more about this since implementing your own API interaction?

If not, I'm tempted to close the issue, because it seems too complicated (out of scope of the gem) to address. If Google is returning incorrect response codes, hopefully it's a temporary condition of the API. Setting expiration times for certain types of results would be a possible solution, but expiration is not something the Geocoder's generalized cache interface can really handle, given that every underlying cache mechanism handles expiration differently.

Hope that makes sense. I am still very interested in dealing with #1089.

**Comment by rdlugosz** [comment]
Not really; I'll occasionally see a failure where the exception looks like this:
`HTTParty::ResponseError: Code 500 - { "results" : [], "status" : "UNKNOWN_ERROR" }`

...but it's pretty uncommon and often resolves itself with future queries. Unsure if this is related to the issue I was seeing; I would think the gem would not store the results in the face of a 500 error, but maybe it would?

You're welcome to close the issue as it sounds like neither of us are able to put a lot of time into this one for now.

**Comment by alexreisner** [comment]
A response with a 500 status from Google would definitely not be cached. It's the responses that are 500s in content but (incorrectly) have a non-500 status that I'm worried about. But, again, I think it's too difficult to test and solve for Google's bugs.
