### ISSUE TITLE
Exception thrown when using mapbox and query contains semicolons

### ISSUE THREAD

**Issue by 12eh** [alexreisner/geocoder#1299]
Mapbox interprets this as multiple queries and returns an array of results. `Geocoder::Lookup::Mapbox` expects it to be a hash, and when it tries a key lookup this throws `TypeError: no implicit conversion of String into Integer`.

### Expected behavior
This is definitely debatable, which is why I'm opening an issue rather than a PR right away. The possibilities I can think of are:
- throw an `ArgumentError` or something with an error message saying multiple-location queries aren't supported
- strip the semicolons out of the query before sending to mapbox (on the off chance that someone's query just happens to contain a semicolon and they don't intend for it to mean multiple separate queries)
- return the result for the first of the queries
- return the highest relevance result out of all the queries
- add support in geocoder for this concept and return an array of results as mapbox does

### Actual behavior
Throwing an exception which doesn't describe what the real issue is

### Steps to reproduce
```
> Geocoder.search('New York, NY;Los Angeles, CA')
TypeError: no implicit conversion of String into Integer
from /app/vendor/bundle/ruby/2.5.0/gems/geocoder-1.4.5/lib/geocoder/lookups/mapbox.rb:20:in `[]'
```

### Environment info

* Geocoder version: 1.4.5
* Rails version: 5.1.4
* Database (if applicable): 
* Lookup (if applicable): mapbox

**Comment by alexreisner** [comment]
Very interesting--thanks for raising this issue! There has been an aborted attempt to add batch geocoding (see discussion at #1046)--maybe this is the time to try again. However, that's a much larger issue and should be handled separately. For now, here's what I think: if Mapbox provides a way to escape a semicolon (so it's interpreted literally, within the address, rather than as a record separator) then I think we should escape them. If not, then maybe truncating the query at the first semicolon makes the most sense (the logic being if Geocoder doesn't support batch queries then we shouldn't make Mapbox run one).

Any support we add for batch queries would require users to put addresses in an array, not a semicolon-delimited string, so this solution is relevant whether or not we implement batch geocoding.

Does that all make sense? Open to discussion.

**Comment by 12eh** [comment]
I don't see anything on https://www.mapbox.com/api-documentation/#geocoding mentioning a way to escape a semicolon (or mentioning semicolons in general). I think truncating the query at the first semicolon is a reasonable solution.

For our application, we're currently just removing all semicolons from the query before even passing to Geocoder, so I have no strong preference for how it's handled at this level.
