### ISSUE TITLE
README within_bounding_box mistake 

### ISSUE THREAD

**Issue by sicoscorpion** [alexreisner/geocoder#1307]
The query `within_bounding_box` takes an array [sw_corner, ne_corner] as documented here in code.
https://github.com/alexreisner/geocoder/blob/bab2e367880b02505dea077951bfada987e2c93d/lib/geocoder/stores/active_record.rb#L61

The README file has it documented as 2 arguments passed directly to `within_bounding_box` which is a mistake.
https://github.com/alexreisner/geocoder#advanced-database-queries

**Comment by alexreisner** [comment]
Because of `bounds.flatten` either argument format works (two arrays or 4 separate args).

**Comment by gl0ng** [comment]
The readme is still incorrect. You have it shown with two arguments instead of one (of type Array):
`
sw_corner = [40.71, 100.23]
ne_corner = [36.12, 88.65]
Venue.within_bounding_box(sw_corner, ne_corner)
`

It should be:
`
sw_corner = [40.71, 100.23]
ne_corner = [36.12, 88.65]
Venue.within_bounding_box([sw_corner, ne_corner])
`

**Comment by alexreisner** [comment]
Ah, now I understand. You're correct. Fixed the gem instead of the readme: 1658b655d66d1ec7c82b61340db0089f44b2eb7a

**Comment by sicoscorpion** [comment]
:laughing:  sorry, i wasn't clear enough. Thanks for the clarification @gl0ngm, that's what i meant.
