### ISSUE TITLE
floating point errors

### ISSUE THREAD

**Issue by ethanj** [alexreisner/geocoder#1323]
Because of not rounding fp vals, the output from this lib is not fully compatible with other standard libs like postgis. For instance, using postgis:

select ST_AsText('point(-71.06540020000001 42.3522691)') 
=> POINT(-71.0654002 42.3522691)

### Expected behavior

geocode '106 Boylston St, Boston, MA'
and its rails equivalent should result in:
Longitude:        -71.0654002

### Actual behavior
Longitude:        -71.06540020000001

### Steps to reproduce
geocode '106 Boylston St, Boston, MA'

### Environment info

* Geocoder version: 1.4.9
* Rails version: 
* Database (if applicable): 
* Lookup (if applicable):

**Comment by alexreisner** [comment]
Hmm...I see what you're saying, but isn't this fuzziness part of the nature of floating point values? In most cases the API returns a string, Geocoder calls `to_f` on that string, and your app stores the resulting floating point value in the database. I suspect you could get more consistent results by using a decimal instead of a floating point database column, but maybe I'm not understanding the question. (ie, I don't understand the incompatibility with PostGIS.)
