### ISSUE TITLE
Retry API requests in case of (certain) failure(s)

### ISSUE THREAD

**Issue by DanielStevenLewis** [alexreisner/geocoder#1342]
### Expected behavior

I would like an option to retry API calls in case the service (e.g., Google Maps) is unavailable, there's a timeout, etc. Ideally one should be able to specify the number of retries and the time between retries, like one can do with Excon.

I couldn't find such an option in the readme.

I feel that this should be built into Geocoder, because as a best practice, clients should be retrying requests to idempotent API endpoints, and it's a nuisance to do so if the functionality isn't part of Geocoder itself, so many users won't do so.

### Actual behavior

N/A

### Steps to reproduce

N/A

### Environment info

* Geocoder version: the latest version at the time of writing this issue.
* Rails version: N/A
* Database (if applicable): 
* Lookup (if applicable):

**Comment by alexreisner** [comment]
Thanks for this suggestion. Unfortunately, it's been mentioned before and I'm not inclined to add it. With a gem like Excon, which makes generic HTTP requests, retry is potentially useful. With Geocoder, there aren't a lot of cases where failures are going to be solved by retrying the request. And in the cases where it might help, it's not the right tool for the job. For example, let's say you configure Geocoder to retry 5 times with a 5-second delay between each. If an API is down for two minutes, this probably isn't going to be sufficient, and you've got a blocking process consuming resources for at least 25 seconds. The right way to do it, in my opinion, is to do all geocoding in background jobs. Sidekiq, ActiveJob, etc are made for exactly this (non-blocking retries). You don't really want to be making external API calls while serving requests anyway, since they're slow.

I think the solution here is to recommend background jobs in the [Performance & Optimization section of the README](https://github.com/alexreisner/geocoder#performance-and-optimization).
