### ISSUE TITLE
Mainstreet and Geocoder

### ISSUE THREAD

**Issue by Twistedben** [alexreisner/geocoder#1344]
Thanks in advanced.

 I installed Mainstreet gem for address verification. Geocoder seemed to come as a dependency. In the console everything seems to be working fine separately, but when trying to create a new address using Mainstreet, I receive a undefined method error for 'formatted_address' for Geocoder::Result::Nominatim
right after the creation should hit the database. I can do direct Geocoder searches and test validation of an address with Mainstreet. I just can't add a row to the Address table without encounter this error. Here's my console: 

> 2.5.0 :071 > Address.create!(street: "1 infinite loop", state: "California", zip_code: "95014")   (0.3ms)  BEGIN
>    (0.4ms)  ROLLBACK
> Traceback (most recent call last):
>         1: from (irb):71
> NoMethodError (undefined method `formatted_address' for #<Geocoder::Result::Nominatim:0x0000000004b2a3c8>)

I'd like for this to be working so the result can be lat and long after adding a new address and for the validation of Mainstreet to go through. 
My address model for this looks like this: 

```
class Address < ApplicationRecord
 acts_as_address
  geocoded_by :address
   after_validation :geocode
    def address
        [street, city, state].compact.join(', ')
    end
end
```

* Geocoder version: 1.5.0
* Rails version: 5.2, Ruby: 2.5.0
* Database (if applicable): PG
* Lookup (if applicable):  Nominatim (Default everything essentially)

**Comment by alexreisner** [comment]
Looks like Mainstreet is calling `formatted_address` on the Geocoder result, which worked when the default lookup was Google. It recently changed to Nominatim, which doesn't return a formatted address, hence no field by that name. You may be able to fix this in your app by configuring the Google lookup instead of Nominatim:

    Geocoder.configure(lookup: :google, api_key: [you have to apply for one])

Geocodio (`:geocodio`) also supports the `formatted_address` method, so that would work too.

But ultimately this should be fixed in Mainstreet--either by using a different lookup or by calling a different method on the result.

**Comment by Twistedben** [comment]
Thanks, Alex. I figured that was the issue, but don't want to use google. I'll see if there is a free one as an alternative. I appreciate it
