### ISSUE TITLE
geocoded_by instance methods latitude and longitude

### ISSUE THREAD

**Issue by ChunAllen** [alexreisner/geocoder#1423]
I have an a database column `location` which has a `latitude` and `longitude`
e.g.
```
location: {
   latitude: 1.304171,
   longitude: 103.83222
}
```
and in my model. I have 
```
geocoded_by :location, latitude: latitude, longitude: longitude

def latitude
   location['latitude']
end

def latitude
   location['longitude']
end
```
I define a instance method `latitude` and `longitude`

### Expected behavior
Rails console
```
Poi.near([1.304171, 103.83222], 5, units: :km)
```
it should return records.

### Actual behavior
Rails console
```
Poi.near([1.304171, 103.83222], 5, units: :km)
```
it returns `[]`

but when I do it an actual column instead of instance method it returns a record.

### Environment info

* Geocoder version: 1.5.1
* Rails version: 5.2.3
* Database (if applicable): 
* Lookup (if applicable):

**Comment by alexreisner** [comment]
What database are you using?

**Comment by ChunAllen** [comment]
@alexreisner PostgresSQL

**Comment by alexreisner** [comment]
When you call `near`, Geocoder executes an SQL query. The problem is that your latitude and longitude columns cannot be accessed with what you've given in your `geocoded_by` line. I believe it will work if you pass a string with SQL for accessing each of the latitude and longitude values. You'll probably need to include the table name as well. However, with this configuration, I don't know if it will be able to assign values for lat/lon. The recommended way of doing this is to use two fully separate columns for lat and lon.
