### ISSUE TITLE
HERE's Geocoder API is in maintenance mode

### ISSUE THREAD

**Issue by Pritilender** [alexreisner/geocoder#1574]
Looks like the gem is using HERE's Geocoder API which, as stated [on their docs](https://developer.here.com/documentation/geocoder/dev_guide/topics/what-is.html) is now in maintenance and they suggest that [Geocoding and Search API](https://developer.here.com/documentation/geocoding-search-api/dev_guide/index.html) should be used instead.

I've observed that there is actual difference in the behaviour (and response, ofc) between these two APIs and that the new API looks to be more accurate. E.g. searching for "29, Shelby, Claire E. Engel Street St. Julians, Malta, STJ1810" via gem returns `[]` while calling the new API directly returns some kind of a result.

I'm happy to provide a PR for this, however I'm not sure whether this should be a separate lookup strategy or the current HERE lookup should be updated.

**Comment by alexreisner** [comment]
Good question! Historically, when APIs are deprecated, we've simply updated Geocoder to point to the new endpoint, and I think that's what we should do here. API responses can change at any time, even without wholesale deprecation/replacement. Geocoder's main responsibility is to manage the query options and make sure not to request anything the API doesn't support. So, if there are changes to Here's query options, it might be good to preserve Geocoder's names for those options, but since the next release will most likely be 1.8.0, I'm not even terribly concerned about that--we can mention any required changes in the release notes. Does that all sound good? (Thanks for offering to make a PR!)
