### ISSUE TITLE
Cannot find certain location like Hotels

### ISSUE THREAD

**Issue by fmoudoute** [alexreisner/geocoder#1648]
BEFORE POSTING AN ISSUE, PLEASE MAKE SURE THE PROBLEM IS NOT ADDRESSED IN THE README!

### Expected behavior
Using the autocomplete field to look up a location, i put the name of the location "Shangri-La Hotel hong Kong" I should be able to see it in the available choices

### Actual behavior
It returns Shangri la Hotel in other cities

### Steps to reproduce
I tried setting up fields, but i am not sure if i am in the right direction:
        $("#geocomplete").geocomplete({
            map: "#my_map",
            backgroundColor: "#ffffff",
            mapOptions: {
                zoom: 10
            },
            markerOptions: {
                draggable: true
            },
            fields: ['geocode', 'restaurant', 'hotel', 'name']
        });
        $("#geocomplete2").geocomplete({
        });

### Environment info

* Geocoder version: geocoder (1.8.1)
* Rails version: Rails 6.1.7

**Comment by alexreisner** [comment]
I'm closing this because this sounds like an issue with the geocoding API you're using. Geocoder's function is to manage API requests and responses, so if you're getting results at all, Geocoder is probably not the issue.

I'm also not sure what Geocoder code you're executing, since you've posted JavaScript. If I'm missing something, though, feel free to clarify and re-open this issue.
