### ISSUE TITLE
Feature request: Async geocoding with sidekiq

### ISSUE THREAD

**Issue by toxin20** [alexreisner/geocoder#593]
It would be convenient to be able to run the geocoding in a worker process like sidekiq or resque

There's a (slightly outdated) fork with sidekiq implemented:
https://github.com/rdeshpande/geocoder/blob/master/lib/geocoder/stores/active_record.rb#L241

Would this be possible at all?

**Comment by richardonrails** [comment]
I also wanted to convert my sync ActiveRecord geocoding:

```rb
  geocoded_by :geocoded_by
  after_validation :geocode, if: :geocoded_by_changed?
```

To conditionally happen async.
One idea was to perhaps have some way to pass a flag when creating/updating, like `model.save(geocode_async: true)`

I understand that I could remove the ActiveRecord geocoding altogether and geocode manually in controllers, but that seems less convenient and I might forget a spot where I update model attributes and forget to geocode.

Ideas welcomed, otherwise I suppose I'll just have to remove all the convenient ActiveRecord bits.

**Comment by richardonrails** [comment]
One other thought is that even if I wanted it to _always_ happen async, it'd be nice to be able to do that with like an `async`  option on the `geocoded_by` flag. Or perhaps it could be done with a custom geocoder that always performs async, while still using the ActiveRecord integration?
