### ISSUE TITLE
`Geocoder::ServiceUnavailable` is not implemented in 1.2.7

### ISSUE THREAD

**Issue by malandrina** [alexreisner/geocoder#816]
`Geocoder::ServiceUnavailable` is referenced in the README but doesn't appear to have been implemented in the 1.2.7 release. It looks like it was implemented a few days after the release: https://github.com/alexreisner/geocoder/commit/49647fa32c4b63c543fc3e7727bc10d1a288a9aa

To avoid confusion, I'd propose removing the reference in the README or updating the README to clarify that `Geocoder::ServiceUnavailable` is only available on `master`. I'd be happy to open a PR to make this change.

**Comment by alexreisner** [comment]
This raises a question I've thought about periodically but have never really dealt with. Because of the way Github works, people view the README on master/HEAD as if it's the definitive README for the latest version of the gem. But it isn't. It's for master/HEAD. In the case you mention, the README is technically correct, you're just looking at the wrong version of it (probably everyone is), because that's the version Github shows by default.

I'm not sure what to do about this. Putting README changes in a separate branch would solve it, but it would also put code and documentation in separate commits/merges, which I don't like (should be able to revert code/doc changes together).

Does that make sense? Any thoughts on that are very welcome.

Also, related to what you point out, note that only a few of the exceptions available in Geocoder are raised by any given lookup, so there's no guarantee that if you configure Geocoder to raise `ServiceUnavailable` that it will actually be raised under those conditions (because most APIs don't return 503 when they should...you may get a timeout instead). Perhaps this is something that should be explained in the README.

**Comment by malandrina** [comment]
> Does that make sense? Any thoughts on that are very welcome.

Yes, definitely! I agree that it’s best to be able to revert code and documentation changes together. I have some thoughts on different approaches I’ve seen.

1. `ActiveModel::Serializers` maintains branches for different releases and has an [enormous, front-and-center disclaimer](https://github.com/rails-api/active_model_serializers#maintenance-please-read) about this in the README. This acts as a useful reminder that the docs you’re viewing on GitHub may not be relevant to the version you’re using on your project.
2. The [`paperclip` README](https://github.com/rails-api/active_model_serializers#maintenance-please-read) explicitly states the following:

> Also, everything in this README might not apply to your version of Paperclip, and you should read the README for version 2.7 instead.

3. The [`factory_girl` README](https://github.com/thoughtbot/factory_girl#documentation) doesn’t include documentation, and instead instructs users to reference documentation “for your version of factory_girl” on Rubygems.

It seems to me like approach no. 2 would be sufficient here and wouldn’t require you to make any changes to your documentation and release workflows. A bullet point in the “Compatibility” section reminding readers that the README on master may not be accurate for the most recent release and pointing them in the direction of [the README as of 1/15](https://github.com/alexreisner/geocoder/blob/34d5752e7fa228f5d711b2c5ad5429b52a482c9b/README.md) would probably work well.

> note that only a few of the exceptions available in Geocoder are raised by any given lookup, so there's no guarantee that if you configure Geocoder to raise ServiceUnavailable that it will actually be raised under those conditions

Good to know. To give you some context, I was working on retry logic for jobs that handle reverse-geocoding records. I figured that in the cases where `TimeoutError`, `SocketError`, or `Geocoder::ServiceUnavailable` are raised, I’d want the jobs to be retried, whereas for exceptions like `Geocoder::InvalidApiKey` I wouldn’t.

> Perhaps this is something that should be explained in the README.

I find I often appreciate descriptions of the conditions which result in custom exceptions being raised, but I also felt like the name of `ServiceUnavailable` did a good job of setting my expectations about its behavior.

**Comment by alexreisner** [comment]
Thanks for the great roundup of approaches to this problem! I agree that 2 should suffice and I like that it keeps the reader on Github (near the code, which is the ultimate source of answers). I just added this to the README: bc4e61b2f38.

I also added this, which is just what I wrote to you about the availability of custom exceptions: c8f5257089.

Thanks also for an explanation of your use case. It makes me think exceptions should be grouped into two categories (network condition, user error/denial) for ease of use in jobs such as yours. Maybe mentioning this in the documentation is enough.

On a related note, are you interested in contributing an ActiveJob for geocoding an object, based on the work you're doing? In the `/examples` directory there's an old sidekiq worker. It would be great to have something that was an ActiveJob and also that was callable from applications using Geocoder, not just sample code.

**Comment by malandrina** [comment]
No problem! The README looks good. I think we can consider this issue resolved.

>  are you interested in contributing an ActiveJob for geocoding an object, based on the work you're doing?

Sure, sounds fun! I took a look at the existing Sidekiq worker and I see what you mean. I'll plan on spending some time on this over the next week.

**Comment by alexreisner** [comment]
Great! Thanks.
