### ISSUE TITLE
Geocoder Truck Factor

### ISSUE THREAD

**Issue by gavelino** [alexreisner/geocoder#893]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Geocoder** and obtained a value of **1**.

The developer responsible for this TF is:

Alex Reisner - author of 69% of the files 

To validate our results, we would like to ask **Geocoder** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Geocoder**?

(b) Do you agree that **Geocoder** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Geocoder** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by alexreisner** [comment]
This is interesting. In short:

a. Yes.
b. It depends what you mean by "in trouble." Geocoder is fairly resilient to external changes because it has no gem dependencies. Therefore if the main developer were to vanish, it would be potentially less urgent than it might be on a project that relied on certain features of, say, Rails. However, geocoding APIs do have a tendency to change with little notice, so in that sense it's less stable than other projects.
c. Not that I can think of, beyond the usual effort towards readable and maintainable code and good documentation.

Do you guys have any recommendations, based on your study?
