### ISSUE TITLE
Add support to MSSQL/TSQL (Azure)

### ISSUE THREAD

**Issue by ipepe** [alexreisner/geocoder#934]
Hello.
Im running rails app on Jruby with MSSQL database but geocoder deosnt support that. Queries have ATAN2 instead of ATN2 of MSSQL. If You need a database I can setup one in azure for the matter of working on that. I You need my help, just tell me.

**Comment by alexreisner** [comment]
Sorry, but I feel similarly about MSSQL as about Oracle (see #535). These databases are not especially popular in the Ruby community and the effort required to add compatibility is quite significant. Only way I could consider adding is if someone submitted a clean pull request (minimal code changes) that included the necessary updates to Travis CI config. Even then, I'd really have to weight the depth and complexity of the code changes against the benefits.

**Comment by ipepe** [comment]
What about doing it like sqlite?

**Comment by alexreisner** [comment]
I don't like how SQLite is handled currently. Ideally there would be separate drivers for each DB system. The way SQLite is currently implemented it's a special case, handled mostly by `if` statements. I don't like the idea of introducing more branches (because it's not good code) or restructuring the whole thing (better code, but deep changes) for functionality that's not core.

**Comment by ipepe** [comment]
based on this: 
http://stackoverflow.com/questions/13026675/calculating-distance-between-two-points-latitude-longitude
I declare that I want to add support to MSSQL. I will create pull request. But before I dive into code, is there a chance for those separate adapters, or maybe just a stub of that?

**Comment by alexreisner** [comment]
OK, you're welcome to submit a PR but just to be clear: there is a good chance I won't merge because I can't currently think of an implementation that I feel comfortable with. Even if not merged, your work will still be useful because you'll be able to install the gem from your own repo. Just wanted to be clear about this.
