### ISSUE TITLE
Mapbox mapbox.places-permanent data source

### ISSUE THREAD

**Issue by marcusat** [alexreisner/geocoder#943]
Please could the new :mapbox option include support for the enterprise-level 'mapbox.places-permanent' alternative to the free 'mapbox.places' source?  Perhaps via an option like:
 Geocoder.configure(mapbox: {source: "mapbox.places-permanent"})

Thanks for an excellent gem!

**Comment by alexreisner** [comment]
Definitely open to a pull request for this. Not sure whether it's better as you suggest or as a separate lookup (that inherits from `Geocoder::Lookups::Mapbox`). Open to discussion.

**Comment by marcusat** [comment]
I'd be happy to work on PRs for this and for the other Mapbox issue.  Re whether better as an option or as a separate lookup I'd defer to whatever you feel is most consistent with the gem's patterns?

**Comment by alexreisner** [comment]
OK, great. I think it lends itself more to being an option within a single lookup, but I'm open to discussion.

As for the bulk lookup feature, because it's outside Geocoder's core functionality, I don't want to introduce any syntax changes to accommodate it. If you want to add that capability (which, while useful, is not core functionality as far as this gem is concerned) maybe add a separate method on the lookup that can be called directly.

**Comment by marcusat** [comment]
For our specific needs we don't plan on using the bulk feature, we just need to use the `mapbox.places-permanent` source to satisfy the Mapbox terms of use, etc.  Hence does feel more like an option to the existing lookup.

I'll take a look at this shortly, just need to determine where this is slotting into our project plan.

**Comment by alexreisner** [comment]
OK, sounds good!

**Comment by alexreisner** [comment]
Added by #946.
