### ISSUE TITLE
Support Postal Town

### ISSUE THREAD

**Issue by dechuck** [alexreisner/geocoder#961]
Hi there,

The method `city` in the `Geocoder::Result::Google` class doesn't support the **postal_town** at the moment. Only `:locality, :sublocality, :administrative_area_level_3, :administrative_area_level_2` here supported.

Let me know if you need more details,
Thanks.

**Comment by alexreisner** [comment]
Google's documentation says:

`postal_town` indicates a grouping of geographic areas, such as `locality` and `sublocality`, used for mailing addresses in some countries.

so I'm not sure `postal_town` gives us any new information. Have you found cases where it does? (I haven't really explored.)

**Comment by dechuck** [comment]
Hey @alexreisner,
I got some issues with some towns in Scotland.

You can try with those coordinate. Latitude: `57.5308931`, Longitude: `-6.152048`
The city's name is Portree, but the gem method returned Highland (the `administrative_area_level_2`).

**Comment by alexreisner** [comment]
In case anyone else wants to see what's going on here, this is the relevant part of the response I'm seeing:

    "address_components"=>[
      {"long_name"=>"A855", "short_name"=>"A855", "types"=>["route"]},
      {"long_name"=>"Portree", "short_name"=>"Portree", "types"=>["postal_town"]},
      {"long_name"=>"Highland", "short_name"=>"Highld", "types"=>["administrative_area_level_2", "political"]},
      {"long_name"=>"United Kingdom", "short_name"=>"GB", "types"=>["country", "political"]},
      {"long_name"=>"IV51 9HX", "short_name"=>"IV51 9HX", "types"=>["postal_code"]}
    ],
    "formatted_address"=>"A855, Portree, Highland IV51 9HX, UK",

So, indeed, the `postal_town` is Portree and the `administrative_area_level_2` is Highland. However, I don't know how to resolve this, or if a resolution is even possible. Should `postal_town` always take precedence over `administrative_area_level_2`?

Place names are complicated, and there are many cases where an area has different names from political and postal perspectives. So, without knowing more, it's hard to say whether this result is "wrong." I'm not completely sure what to do here, but I'm sort of inclined to leave things how they are, since the postal value (here Portree) is returned in the `street_address`.

**Comment by TrangPham** [comment]
If the UK is the only place that uses postal town then it'll be easier to decide the precedence in which to add `:postal_town`.  Occurring to https://en.wikipedia.org/wiki/Post_town
Locality is used as a neighborhood in the UK mailing system, and postal town is the actual town and/or city. In your example there doesn't seem to be a :locality listed. Perhaps adding `:postal_town` after `:locality` and before `:administrative_area_level_2` is a good option?

If the UK isn't the only place which uses `:postal_town` then I would prefer not to add `:postal_town` as we don't know how this could affect other countries

**Comment by alexreisner** [comment]
My concern here is that there are often at least two different systems for naming places: postal and political. "Administrative area" refers to the political system and "postal town" obviously refers to the postal system. I don't think it's a good idea to combine the two. Closing this for now.
