### ISSUE TITLE
The Geocoder is returning an empty array (but works fine on console)

### ISSUE THREAD

**Issue by nonato** [alexreisner/geocoder#989]
Hello good afternoon.

I am facing a strange problem.

The Geocoder is returning an empty array.

It is returning [] when I run the following command directly in html view
Geocoder.search ("São Paulo, São Paulo, Brazil")

But when I run the same command on the rails console, it returns the data correctly (place, lat, long, etc.).

I've changed the timeout to 100, 200, and still does not work.

In fact, 90% of the time does not work. But sometimes, without any explanation it works.

What could be wrong?

I am using the latest version.

Thanks in advance.

**Comment by TrangPham** [comment]
Hi

Which lookup are you using? could it be that you're sometimes reaching your
query limit?

**Comment by nonato** [comment]
Hello, thanks for response.

I am using google.

Here is my geocoder config.


Geocoder.configure(
  # geocoding service
  lookup: :google,

  # geocoding service request timeout (in seconds)
  timeout: 30,

  # default units
  units: :km
)



Is something wrong?

Thank you

**Comment by TrangPham** [comment]
Hi @nonato 

I was unable to reproduce that error.
I created a new rails app 4.2.0, ruby 2.3 and tried doing the 
```ruby
<%= Geocoder.search ("São Paulo, São Paulo, Brazil") %>
```
in my html.erb and did not have any issues.

**Comment by nonato** [comment]
Hello. tanks for response.

Can it be a problem with the version of rails?

I'm using 3.2.3.

I really do not understand.

Even so, thank you for your attention.

**Comment by alexreisner** [comment]
If it works in the console, chances are that the problem is not related to Rails or Geocoder. My suggestion for debugging is to think about the ways running the command in the console is different from running it in a view. What happens in a controller, for example? Is there caching? What are the differences in environment between console and view that could be affecting this? Without knowing a lot more about your app, it's hard to know what to suggest.
